main/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^AGI_list$', views.AGI_list, name='AGI_list'),
]

suggestions/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

main/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
#
# Also note: You'll have to insert the output of 'django-admin sqlcustom [app_label]'
# into your database.
from __future__ import unicode_literals

from django.db import models

class Species(models.Model):
    species_name = models.CharField(max_length=50)
    short_name = models.CharField(max_length=45)
    url = models.CharField(max_length=255)

    class Meta:
        managed = False
        db_table = 'main_species'


class Chromosome(models.Model):
    name = models.CharField(max_length=50)
    start = models.IntegerField()
    end = models.IntegerField()
    species = models.ForeignKey(Species)
	
    class Meta:
        managed = False
        db_table = 'main_chromosome'


class Experiment(models.Model):
    species = models.ForeignKey(Species)
    name = models.CharField(max_length=50)
    phenotypes = models.CharField(max_length=50)
    type_of_array = models.CharField(max_length=50)
    sample_size = models.CharField(max_length=50)
    parental_strain = models.CharField(max_length=50)
    sample = models.CharField(max_length=100)
    reference = models.CharField(max_length=200)
    pub_url = models.URLField(max_length=300)
    pub_date = models.DateTimeField()
    upload_user_id = models.IntegerField()
    array_file = models.CharField(max_length=100)
    marker_file = models.CharField(max_length=100)
    genotype_file = models.CharField(max_length=100)
    lod_file = models.CharField(max_length=100)
    pvalthld = models.DecimalField(max_digits=13, decimal_places=12)
    lodthld = models.DecimalField(max_digits=6, decimal_places=3)

    class Meta:
        managed = False
        db_table = 'main_experiment'


class Line(models.Model):
    experiment = models.ForeignKey(Experiment)
    line_name = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'main_line'


class Marker(models.Model):
    name = models.CharField(max_length=40)
    chromosome = models.ForeignKey(Chromosome)
    start = models.IntegerField(blank=True, null=True)
    end = models.IntegerField(blank=True, null=True)
    experiment = models.ForeignKey(Experiment)

    class Meta:
        managed = False
        db_table = 'main_marker'
        
class Marker_Experiment(models.Model):
    experiment = models.ForeignKey(Experiment)
    marker = models.ForeignKey(Marker)

    class Meta:
        managed = False
        db_table = 'main_marker_experiment'

class GeneInfo(models.Model):
    species = models.ForeignKey(Species) 
    gene_id = models.CharField(max_length=30, blank=True, null=True, unique=True)
    description = models.TextField(blank=True,null=True)
    gene_name = models.CharField(max_length=30, blank=True, null=True, unique=True)
    chr = models.CharField(max_length=3)
    start = models.IntegerField(blank=True, null=True)
    end = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'main_geneinfo'

class Transcript(models.Model): 
    geneinfo = models.ForeignKey(GeneInfo)
    transcript_id = models.CharField(max_length=20, blank=True, null=True)
    chr = models.CharField(max_length=3)
    start = models.IntegerField(blank=True, null=True)
    end = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'main_transcript'


class GO(models.Model):
    accession = models.CharField(primary_key=True,max_length=30,blank=False,null=False, unique=True)
    name = models.CharField(max_length=255,blank=False,null=False)
    definition = models.TextField()
    domain = models.CharField(max_length=255,blank=False,null=False)

    class Meta:
        managed = False
        db_table = 'main_go'

class GeneGO(models.Model):
    geneinfo = models.ForeignKey(GeneInfo)
    term_accession = models.ForeignKey(GO,to_field='accession', db_column = 'term_accession')
    term_evidence_code = models.CharField(max_length=30,blank=False,null=False)

    class Meta:
        managed = False
        db_table = 'main_gene_go'

class Gene_Experiment(models.Model):
    experiment = models.ForeignKey(Experiment)
    geneinfo = models.ForeignKey(GeneInfo)
    gene_id = models.CharField(max_length=50)
    max_lod_score = models.FloatField()

    class Meta:
        managed = False
        db_table = 'main_gene_experiment'

class Phenotype(models.Model):
    phenotype_id = models.CharField(max_length=255, blank=False, null=False, unique=True)
    name = models.CharField(max_length=255,blank=False,null=False)
    description = models.TextField(blank=True,null=True)
    phenotype = models.TextField(blank=True,null=True)
    treatment = models.TextField(blank=True,null=True)
    trait = models.TextField(blank=True,null=True)
    statistic = models.TextField(blank=True,null=True)
    stage = models.TextField(blank=True,null=True)
    population = models.TextField(blank=True,null=True)
    unit = models.TextField(blank=True,null=True)
    comment = models.TextField(blank=True,null=True)
    GO_term = models.TextField(blank=True,null=True)

    class Meta:
        managed = False
        db_table = 'main_phenotype'

class Phenotype_Experiment(models.Model):
    experiment = models.ForeignKey(Experiment)
    phenotype = models.ForeignKey(Phenotype)
    max_lod_score = models.FloatField()

    class Meta:
        managed = False
        db_table = 'main_phenotype_experiment'

suggestions/models.py
from django.db import models

# Create your models here.

suggestions/views.py
import urllib2

from django.conf import settings
from django.shortcuts import render_to_response, HttpResponse

from main.models import GeneInfo, GO, GeneGO, Experiment, Phenotype

class GOTerm:
    accesssion = ""
    name = ""
    definition = ""
    domain = ""
    gene_count = 0

def index(request):
    if request.method == 'GET':

        if request.GET.get('query') and request.GET.get('experiment_name'):
            query = request.GET.get('query')
            query = urllib2.unquote(query).strip()
            experiment_name = request.GET.get('experiment_name')

            return suggest(query,experiment_name, None)

    return suggest(None,None,None)

def suggest(query, experiment_name, mode):
    experiments = Experiment.objects.filter(species__species_name=settings.SPECIES)

    if not query:
        phenotypes = Phenotype.objects.all()
        return render_to_response('suggestions.html', {'Phenotypes': phenotypes,
                                                   'mode': mode,
                                                   'experiments': experiments,
                                                   'experiment_name': experiment_name})
                                                   
    if query == "FullGO":
        
        GO_terms = GO.objects.filter(genego__isnull=False).distinct()
            
        return render_to_response('suggestions.html', {
                                                'GOterms': GO_terms,
                                                'mode': mode,
                                                'experiments': experiments,
                                                'experiment_name': experiment_name})

    GO_terms = list(GO.objects.raw(
        "select * from main_go WHERE MATCH (name, definition) AGAINST ('%s' IN NATURAL LANGUAGE MODE)" % query))

    genes = list(GeneInfo.objects.raw(
        "select * from main_geneinfo WHERE MATCH (gene_name, description) AGAINST ('%s' IN NATURAL LANGUAGE MODE)" % query))

    gene_substring_results = GeneInfo.objects.filter(gene_name__icontains = query)

    for gene in gene_substring_results:
        genes.append(gene)

    genes = list(set(genes))

    phenotypes = list(Phenotype.objects.raw(
        "select * from main_phenotype WHERE MATCH (name, description,treatment,trait) AGAINST ('%s' IN NATURAL LANGUAGE MODE)" % query))

    if len(genes) == 0 and len(GO_terms) == 0 and len(phenotypes) == 0:
        return None

    return render_to_response('suggestions.html', {'Genes': genes,
                                                   'GOterms': GO_terms,
                                                   'Phenotypes': phenotypes,
                                                   'mode': mode,
                                                   'experiments': experiments,
                                                   'experiment_name': experiment_name})

suggestions/templates/suggestions.html
{% extends 'base.html' %}

{% block content %}

{% load staticfiles %}

<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
<link rel="stylesheet" href="{% static 'css/datatables.min.css' %}"/>
<link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css" xmlns="http://www.w3.org/1999/html"/>
<script type="text/javascript" src="/EleQTL/static/js/bootstrap.min.js"></script>
<script type="text/javascript" src="{% static 'js/datatables.min.js' %}"></script>

<nav class="navbar navbar-nav navbar-fixed-top">
    <div class="container-fluid">
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav nav-pills">
                <li><a class="navbar-brand" href="/EleQTL" id="home_button">WormQTL2</a></li>
                <li{% if mode == 'correlation' %} class="active"{% endif %}><a
                    href="/EleQTL/?mode=correlation">Correlation</a></li>
                <li{% if mode == 'coregulation' %} class="active"{% endif %}><a
                    href="/EleQTL/?mode=coregulation">Locus</a></li>
                <form class="navbar-form navbar-left" action="/EleQTL/multiplot/" method="get" id="top_form">
                    <input title="Type your query here" id="query" name="query" type="text" class="form-control"
                           placeholder="Search...">
                    <select title="Select an experiment" class="form-control" id="experiment_selector" name="experiment_name">
                        {% for experiment in experiments %}
                        <option value="{{ experiment.name }}" {% if experiment.name == experiment_name %} selected {% endif %}>
                            {{ experiment.name }}
                        </option>
                        {% endfor %}
                        <option value="all" {% if experiment_name == "all" %} selected {% endif %}>all</option>
                    </select>
                </form>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Help
                        <span class="caret"></span></a>
                    <ul class="dropdown-menu dropdown-menu-left">
                        <li><a href="{% static 'about.html' %}">About</a></li>
                        <li><a href="{% static 'Manual.html' %}">Manual</a></li>
                        <li><a href="{% static 'FAQ.html' %}">FAQ</a></li>
                        <li><a href="/EleQTL/?mode=methods">Methods</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div id="container" align="center">
<table cellspacing='0'>
<tr><td>Found: 
{% if Genes|length > 0 %} <a href="#Genes">{{ Genes|length }} gene{% if Genes|length != 1 %}s{% endif %}</a>&nbsp;{% endif %}
{% if Phenotypes|length > 0 %} <a href="#Phenotypes">{{ Phenotypes|length }} phenotype{% if Phenotypes|length != 1 %}s{% endif %}</a>&nbsp;{% endif %}
{% if GOterms|length > 0 %} <a href="#GOterms">{{ GOterms|length }} GO term{% if GOterms|length != 1 %}s{% endif %}</a>&nbsp;{% endif %}
</td></tr></table>
{% if Genes|length > 0 %}
<a name="Genes"></a>
<table cellspacing='0' class="suggestions_table">
    <thead>
	<tr>
              <th>ID</th>
              <th>Name</th>
              <th>Max lod score</th>
              <th>Description</th>
        </tr>
        </thead>
        <tbody>
{% for gene in Genes %}
	<tr>
        <td>
            {% if mode == 'correlation' %}
            <A href="/EleQTL/correlation/?query={{ gene.gene_id|upper }}&experiment_name={{ experiment_name }}">{{ gene.gene_id }}</a>
            {% elif mode == 'coregulation' %}
            <A href="/EleQTL/coregulation/?query={{ gene.gene_id|upper }}&experiment_name={{ experiment_name }}">{{ gene.gene_id }}</a>
            {% else %}
            <A href="/EleQTL/multiplot/?query={{ gene.gene_id|upper }}&experiment_name=all">{{ gene.gene_id }}</a>
            {% endif %}
        </td>
        <td>{{ gene.gene_name }}</td>
        <td>{{ gene.max_lod }}</td>
		<td title="{{ gene.description }}">{{ gene.description }}</td>
        </tr>
{% endfor %}
</tbody>
</table>
{% endif %}
{% if Phenotypes|length > 0 %}
<a name="Phenotypes" align=left></a>
    <br><br>
         <button onclick="plot_selected_phenotypes()" title="Plots the QTL profiles the selected trait IDs">Plot selected traits</button>
<table cellspacing='0' class="suggestions_table">
    <thead>
	<tr>       <th><input type="checkbox" name="alltraits_checkbox" value="all"></th>
              <th>Phenotype</th>
              <th>treatment</th>
              <th>trait</th>
              <th>statistic</th>
              <th>stage</th>
              <th>population</th>
              <th>unit</th>
              <th>GO_term</th>
              <th>Experiment(s)</th>
        </tr>
        </thead>
        <tbody>
    {% for phenotype in Phenotypes %}
	<tr>
        <td><input type="checkbox" name="trait_checkbox" value="{{ forloop.counter0 }}"></td>
        <td>
            {% if mode == 'correlation' %}
            <a href="/EleQTL/correlation/?query={{ phenotype.phenotype_id }}&experiment_name={{ experiment_name }}">
                {{ phenotype.name }}
            </a>
            {% elif mode == 'coregulation' %}
            <a href="/EleQTL/coregulation/?query={{ phenotype.phenotype_id }}&experiment_name={{ experiment_name }}">
                {{ phenotype.name }}
            </a>
            {% else %}
            <a href="/EleQTL/multiplot/?query={{ phenotype.phenotype_id }}&experiment_name=all">
                {{ phenotype.name }}
            </a>
            {% endif %}
        </td>
        <td>{{ phenotype.treatment  }}</td>
        <td>{{ phenotype.trait  }}</td>
        <td>{{ phenotype.statistic  }}</td>
        <td>{{ phenotype.stage  }}</td>
        <td>{{ phenotype.population  }}</td>
        <td>{{ phenotype.unit  }}</td>
        <td>{{ phenotype.GO_term  }}</td>       
        <td>{% for e in phenotype.phenotype_experiment_set.all %}
        <a href="/EleQTL/multiplot/?query=all&experiment_name={{ e.experiment.name }}">
            {{ e.experiment.name }}
        </a><br>
        {% endfor %}</td>
        </tr>
{% endfor %}
</tbody>
</table>
{% endif %}
{% if GOterms|length > 0 %}
<a name="GOterms" align=left></a>
    <br><br>
<table cellspacing='0' class="suggestions_table">
    <thead>
	<tr>
              <th>GO term</th>
              <th>Genes</th>
              <th>Name</th>
              <th>Definition</th>
        </tr>
        </thead>
        <tbody>    
    {% for GOterm in GOterms %}
	<tr>
        <td>
            <a href="/EleQTL/multiplot/?query={{ GOterm.accession|upper }}&experiment_name={{ experiment_name }}">
                {{ GOterm.accession }}
            </a>
        </td>
        <td>{{ GOterm.genego_set.count }}</td>
        <td>{{ GOterm.name }}</td>
		<td title="{{ GOterm.definition }}">{{ GOterm.definition }}</td>
        </tr>
{% endfor %}
</tbody>
</table>
{% endif %}
</div>

<script>
    var phenotypes = [];
    {% for phenotype in Phenotypes %}
        phenotypes[{{ forloop.counter0 }}] = "{{ phenotype.name|upper }}";
    {% endfor %}
     function plot_selected_phenotypes() {
            var checked_values = $('input[name="trait_checkbox"]:checked').map(function() {
					    return this.value;
					}).get();
            
            var checked_length = checked_values.length;
            if (checked_length == 0) {
                return;
            }
            var query = "";
            var sep = "";
            for (var j = 0; j < checked_length; j++) {
                query += sep + phenotypes[checked_values[j]];
                sep = "+";
            }
            
            window.location.href = "/EleQTL/multiplot/?query="+query+"&experiment_name=all";
       }
       $('input[name="alltraits_checkbox"]').click(function() {
            if ($('input[name="alltraits_checkbox"]').is(':checked')) {
                    $('input[name="trait_checkbox"]').prop("checked", true);
            } else {
                    $('input[name="trait_checkbox"]').prop("checked", false);
            }
       });
       
       $('select#experiment_selector').change(function() {
            $('form#top_form').submit();
       });
       $('.suggestions_table').DataTable({
                 "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
                 paging: false
                 } );
</script>
{% endblock %}