download/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

main/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^AGI_list$', views.AGI_list, name='AGI_list'),
]

download/models.py
from django.db import models

# Create your models here.

main/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
#
# Also note: You'll have to insert the output of 'django-admin sqlcustom [app_label]'
# into your database.
from __future__ import unicode_literals

from django.db import models

class Species(models.Model):
    species_name = models.CharField(max_length=50)
    short_name = models.CharField(max_length=45)
    url = models.CharField(max_length=255)

    class Meta:
        managed = False
        db_table = 'main_species'


class Chromosome(models.Model):
    name = models.CharField(max_length=50)
    start = models.IntegerField()
    end = models.IntegerField()
    species = models.ForeignKey(Species)
	
    class Meta:
        managed = False
        db_table = 'main_chromosome'


class Experiment(models.Model):
    species = models.ForeignKey(Species)
    name = models.CharField(max_length=50)
    phenotypes = models.CharField(max_length=50)
    type_of_array = models.CharField(max_length=50)
    sample_size = models.CharField(max_length=50)
    parental_strain = models.CharField(max_length=50)
    sample = models.CharField(max_length=100)
    reference = models.CharField(max_length=200)
    pub_url = models.URLField(max_length=300)
    pub_date = models.DateTimeField()
    upload_user_id = models.IntegerField()
    array_file = models.CharField(max_length=100)
    marker_file = models.CharField(max_length=100)
    genotype_file = models.CharField(max_length=100)
    lod_file = models.CharField(max_length=100)
    pvalthld = models.DecimalField(max_digits=13, decimal_places=12)
    lodthld = models.DecimalField(max_digits=6, decimal_places=3)

    class Meta:
        managed = False
        db_table = 'main_experiment'


class Line(models.Model):
    experiment = models.ForeignKey(Experiment)
    line_name = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'main_line'


class Marker(models.Model):
    name = models.CharField(max_length=40)
    chromosome = models.ForeignKey(Chromosome)
    start = models.IntegerField(blank=True, null=True)
    end = models.IntegerField(blank=True, null=True)
    experiment = models.ForeignKey(Experiment)

    class Meta:
        managed = False
        db_table = 'main_marker'
        
class Marker_Experiment(models.Model):
    experiment = models.ForeignKey(Experiment)
    marker = models.ForeignKey(Marker)

    class Meta:
        managed = False
        db_table = 'main_marker_experiment'

class GeneInfo(models.Model):
    species = models.ForeignKey(Species) 
    gene_id = models.CharField(max_length=30, blank=True, null=True, unique=True)
    description = models.TextField(blank=True,null=True)
    gene_name = models.CharField(max_length=30, blank=True, null=True, unique=True)
    chr = models.CharField(max_length=3)
    start = models.IntegerField(blank=True, null=True)
    end = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'main_geneinfo'

class Transcript(models.Model): 
    geneinfo = models.ForeignKey(GeneInfo)
    transcript_id = models.CharField(max_length=20, blank=True, null=True)
    chr = models.CharField(max_length=3)
    start = models.IntegerField(blank=True, null=True)
    end = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'main_transcript'


class GO(models.Model):
    accession = models.CharField(primary_key=True,max_length=30,blank=False,null=False, unique=True)
    name = models.CharField(max_length=255,blank=False,null=False)
    definition = models.TextField()
    domain = models.CharField(max_length=255,blank=False,null=False)

    class Meta:
        managed = False
        db_table = 'main_go'

class GeneGO(models.Model):
    geneinfo = models.ForeignKey(GeneInfo)
    term_accession = models.ForeignKey(GO,to_field='accession', db_column = 'term_accession')
    term_evidence_code = models.CharField(max_length=30,blank=False,null=False)

    class Meta:
        managed = False
        db_table = 'main_gene_go'

class Gene_Experiment(models.Model):
    experiment = models.ForeignKey(Experiment)
    geneinfo = models.ForeignKey(GeneInfo)
    gene_id = models.CharField(max_length=50)
    max_lod_score = models.FloatField()

    class Meta:
        managed = False
        db_table = 'main_gene_experiment'

class Phenotype(models.Model):
    phenotype_id = models.CharField(max_length=255, blank=False, null=False, unique=True)
    name = models.CharField(max_length=255,blank=False,null=False)
    description = models.TextField(blank=True,null=True)
    phenotype = models.TextField(blank=True,null=True)
    treatment = models.TextField(blank=True,null=True)
    trait = models.TextField(blank=True,null=True)
    statistic = models.TextField(blank=True,null=True)
    stage = models.TextField(blank=True,null=True)
    population = models.TextField(blank=True,null=True)
    unit = models.TextField(blank=True,null=True)
    comment = models.TextField(blank=True,null=True)
    GO_term = models.TextField(blank=True,null=True)

    class Meta:
        managed = False
        db_table = 'main_phenotype'

class Phenotype_Experiment(models.Model):
    experiment = models.ForeignKey(Experiment)
    phenotype = models.ForeignKey(Phenotype)
    max_lod_score = models.FloatField()

    class Meta:
        managed = False
        db_table = 'main_phenotype_experiment'

download/views.py
from django.shortcuts import HttpResponse
from django.views.decorators.csrf import csrf_exempt

import re

@csrf_exempt
def index(request):
    download_data = ""
    if request.method == 'GET':
        if request.GET.get('data'):
            download_data = request.GET.get('data');
            download_data = re.sub(",","\n",download_data)
    elif request.method == 'POST':
        if request.POST.get('data'):
            download_data = request.POST.get('data');
            download_data = re.sub(",","\n",download_data)

    return HttpResponse(download_data, content_type='text/plain')

main/views.py
from django.shortcuts import render_to_response
from django.http import HttpResponse
from django.conf import settings

from main.models import Experiment, Gene_Experiment

import csv

def index(request):
    experiments = Experiment.objects.filter(species__species_name=settings.SPECIES)

    mode = 'landing'

    if request.method == 'GET':
        if request.GET.get('mode'):
            mode = request.GET.get('mode')

    return render_to_response('index.html',{'experiments':experiments,
                                            'mode' :mode})

def no_results(query, mode):
    experiments = Experiment.objects.filter(species__species_name=settings.SPECIES)

    return render_to_response('index.html', {'experiments': experiments,
                                             'query': query,
                                             'noresults': 1,
                                             'mode': mode})


def AGI_list(request):
    genelist = Gene_Experiment.objects.filter(experiment__species__species_name=settings.SPECIES).values_list('gene_id', flat=True)
    AGI_list = '\n'.join(genelist)

    response = HttpResponse(content_type='text/plain')
    response['Content-Disposition'] = 'attachment; filename="ELEQTL_ID_list.txt"'
    response.write(AGI_list)

    return response

main/templates/FAQ.html
<div id="FAQ_text">
    <h1>FAQ</h1>
    <ul>
        <li><i>How can I add studies to WormQTL 2?</i><br>
        Send an email to wormqtl2@bioinformatics.nl
        </li>
	<li><i>Does WormQTL 2 work in all browsers?</i><br>
	In principle it should work on all browsers that support Javascript. We do recommend using Firefox, since WormQTL 2 was extensively tested with that browser.
	</li>
        <li><i>What are the error and interval size of the eQTLs?</i><br>
            The maps are linked by the physical position of the markers.
            The exact marker positions can be downloaded from the website.
            If the confidence intervals (for instance of 2-LOD) of two eQTLs overlap it is likely the same eQTL,
            especially in the case of cis-eQTLs.
        </li>
    </ul>
</div>

main/templates/about.html
<div id="about_text">
    <div class="paragraph">
    <h1>WormQTL 2</h1>
    WormQTL 2 is a web-based workbench and database for expression quantitative trait locus (eQTL) investigation.
    Its aim is to support the C.elegans community to use eQTL data in their research.<br>

    </div>
     <div class="paragraph">
    Created by Harm Nijveen, Mark Sterken &amp; Basten Snoek.<br><br>
         Wageningen University <a href="https://www.bif.wur.nl/">Bioinformatics Group</a>,
         <a href="https://www.nem.wur.nl/">Laboratory of Nematology</a>
         &amp; <a href="https://www.wur.nl/en/Expertise-Services/Chair-groups/Plant-Sciences/Laboratory-of-Plant-Physiology/Wageningen-Seed-Lab.htm">Wageningen Seed Lab</a><br><br>
    With collaborators:<br>
         Wilco Ligterink, Jiao Long, Joost Keurentjes, Henk Hilhorst, Jan Kammenga, Oliver Loudet, Pjotr Prins, Mark Sterken &amp; Dick de Ridder<br><br>
Using <a href="https://github.com/kbroman/d3examples/tree/master/cistrans">cistrans</a> code by Karl Broman
</div>
    <div class="paragraph">
WormQLT2 was modelled after
    <A href="https://onlinelibrary.wiley.com/doi/10.1111/tpj.13457/full">
AraQTL
    </A> (the arabidopsis eQTL resource).<br><br>
        A paper describing WormQTL2 was published in <i>Database</i>:<br>
    <A href="https://doi.org/10.1093/database/baz149">
        WormQTL2: an interactive platform for systems genetics in Caenorhabditis elegans
    </A>
        </div>
</div>

main/templates/download.html
<div id="download_text">
    <center>
    <table id="table">
        <thead>
        <tr>
            <th>Experiment</th>
            <th>LOD score</th>
            <th>Marker</th>
            <th>Map</th>
            <th>Expression data</th>
        </tr>
        </thead>
        <tbody>
        {% for experiment in experiments %}
                    <tr>
                        <td>
                            {{ experiment.name }}
                        </td>

                        <td align="left">
                            <a href="/EleQTL/media/data/{{ experiment.name }}/lod{% if experiment.gene_experiment_set.count == 0 %}_phenotypes{% endif %}.txt"
                               target="_blank"
                               title="right click to save as..."
                            >
                            lod.txt
                            </a>
                        </td>
                        <td>
                            <a href="/EleQTL/media/data/{{ experiment.name }}/marker.txt"
                               target="_blank"
                               title="right click to save as..."
                            >
                            marker.txt
                            </a>
                        </td>
                                                <td>
                            <a href="/EleQTL/media/data/{{ experiment.name }}/map.txt"
                               target="_blank"
                               title="right click to save as..."
                            >
                            map.txt
                            </a>
                        </td>
                                                <td>
                            <a href="/EleQTL/media/data/{{ experiment.name }}/phenotypes.txt"
                               target="_blank"
                               title="right click to save as..."
                            >
                            phenotypes.txt
                            </a>
                        </td>
                    </tr>
        {% endfor %}
        </tbody>
        </table>

</div>

main/templates/manual.html
<div id="manual_text">
     <div class="paragraph">
<h1>EleQTL</h1>
Download the <a href="/EleQTL/static/EleQTL_manual.pdf">EleQTL manual</a><br><br>
EleQTL is a web-based workbench and database for expression quantitative trait loci (eQTL) investigation.<br>
It’s aim is to support the i<i>C.elegans</i> genetics community to utilities eQTL data in their research.<br>
Currently it holds publicly available data of all published <i>C.elegans</i> eQTL studies. 
</div>
    <div class="paragraph">

<a href="/EleQTL/cistrans/?experiment_name=Vinuela_Snoek_etal_2010_juvenile"><img src="/EleQTL/static/image/cistrans.png" width="350" align="right"></a>
    <h3>Cis/Trans Plot</h3>
    To get a genome-wide overview of the distribution of eQTL Cis/Trans Plot is most frequently used (REFs). The position of the eQTL peak is plotted on the x-axis against the position the genes for which these eQTL peak were found. We provide a default eQTL peak significance threshold per experiment at FDR of 0.05 for quick visualisation and an option to manually adjust this threshold for further exploration. The diagonal line of points show the Cis-eQTLs whereas so called hotspots or transbands can be recognized as vertical lines of points.
    This Cis/Trans plot has been made interactive by being able to select different experiment by a drop-down menu. Moreover the individual peaks (points in the Cis/Trans Plot) can be clicked to show the complete eQTL profile of the selected gene/peak. Lastly, the peak frequency per marker is show in the barplot below the Cis/Trans plot. Individual bars/markers can be clicked to obtain a figure and list with genes sharing a peak on the selected marker.  </p>
</div>
    <div class="paragraph">

<a href="/EleQTL/multiplot/?query=WBGENE00020592&experiment_name=all"><img src="/EleQTL/static/image/multiQTL.png" width="350" align="right"></a>
<h3>Gene eQTL profiles</h3>
        In the “Gene eQTL profiles” window gene specific eQTL patterns between experiments can be compared. In this way experiment specific and co-occurring eQTLs can be easily recognised. Genes can be search and selected by a search box. The figure is interactive as points on the profile can be clicked which opens the window showing genes with an eQTL at the clicked marker in the selected experiment.
</div>
<div class="paragraph">
<a href="/EleQTL/coregulation/?query=V%3A4887173&experiment_name=Vinuela_Snoek_etal_2010_juvenile"><img src="/EleQTL/static/image/coregulation.png" width="350" align="right"></a>
    <h3>Shared peaks</h3>
To find genes with an eQTL at the same locus the “Shared peaks” window can be used. The profile of the ten genes with the highest LOD score is show in the figure and a list with all genes with a peak above the threshold is place below the figure. Experiment, marker and threshold can be selected.
</div>
<div class="paragraph">
<a href="/EleQTL/correlation/?query=WBGENE00020592&corrthld=0.8&experiment_name=Rockman_etal_2010"><img src="/EleQTL/static/image/correlation.png" width="350" align="right"></a>
    <h3>Correlated eQTL profiles</h3>
Extending from co-location of eQTL peaks the “Correlating eQTL profiles” window can be used to find genes with a correlated eQTL profile. This shows genes highly likely controlled by the loci (genetic architecture). Experiment, gene and correlation threshold can be selected. Specific peaks in the figures can be clicked to find genes sharing eQTLs at the selected marker.
</div>
</div>

main/templates/methods.html
<div id="methods_text">
    <div class="paragraph">
        <h1>Methods</h1>
eQTL profiles mapped in the original papers are used for visualization and investigation, except for those found in Lowry et al. 2013 which were re-mapped from the original genotypes and gene expression data by a single marker model using a linear model in R. 
    </div>

    <div class="paragraph">
        <h3>Correlation</h3>
All pairwise correlations between eQTL patterns were calculated using the Pearson correlation coefficients between the eQTL patterns of genes within an experiment using the R function ‘cor’, on the LOD scores. 
    </div>

    <div class="paragraph">
        <h3>Mapping</h3>
The markers are mapped according to the original publications. The physical positions of the markers were used to compare and integrate the genetic maps of the different populations and can be obtained from the WormQTL 2 homepage. 
    </div>

    <div class="paragraph">
        <h3>LOD score threshold</h3>
The LOD score thresholds are taken from the corresponding papers. Original determined genome-wide threshold levels may be applied to call significant eQTLs. The thresholds for comparing eQTLs will vary depending on the number of genes, eQTLs and populations involved. 
    </div>

    <div class="paragraph">
        <h3>Software</h3>
WormQTL 2 was implemented in the Python Django web framework using a MySQL database backend. The web pages include Javascript, using JQuery, and the d3 and bootstrip libraries. The cis/trans plot and QTL profile plots built upon work by Karl Broman <a href="http://www.genetics.org/content/199/2/359.long">(Broman, 2015)</a>.
    </div>
</div>